/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { RawMaterial } from "./RawMaterial";
import { RawMaterialCountArgs } from "./RawMaterialCountArgs";
import { RawMaterialFindManyArgs } from "./RawMaterialFindManyArgs";
import { RawMaterialFindUniqueArgs } from "./RawMaterialFindUniqueArgs";
import { CreateRawMaterialArgs } from "./CreateRawMaterialArgs";
import { UpdateRawMaterialArgs } from "./UpdateRawMaterialArgs";
import { DeleteRawMaterialArgs } from "./DeleteRawMaterialArgs";
import { Supplier } from "../../supplier/base/Supplier";
import { RawMaterialService } from "../rawMaterial.service";
@graphql.Resolver(() => RawMaterial)
export class RawMaterialResolverBase {
  constructor(protected readonly service: RawMaterialService) {}

  async _rawMaterialsMeta(
    @graphql.Args() args: RawMaterialCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [RawMaterial])
  async rawMaterials(
    @graphql.Args() args: RawMaterialFindManyArgs
  ): Promise<RawMaterial[]> {
    return this.service.rawMaterials(args);
  }

  @graphql.Query(() => RawMaterial, { nullable: true })
  async rawMaterial(
    @graphql.Args() args: RawMaterialFindUniqueArgs
  ): Promise<RawMaterial | null> {
    const result = await this.service.rawMaterial(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => RawMaterial)
  async createRawMaterial(
    @graphql.Args() args: CreateRawMaterialArgs
  ): Promise<RawMaterial> {
    return await this.service.createRawMaterial({
      ...args,
      data: {
        ...args.data,

        supplier: args.data.supplier
          ? {
              connect: args.data.supplier,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => RawMaterial)
  async updateRawMaterial(
    @graphql.Args() args: UpdateRawMaterialArgs
  ): Promise<RawMaterial | null> {
    try {
      return await this.service.updateRawMaterial({
        ...args,
        data: {
          ...args.data,

          supplier: args.data.supplier
            ? {
                connect: args.data.supplier,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => RawMaterial)
  async deleteRawMaterial(
    @graphql.Args() args: DeleteRawMaterialArgs
  ): Promise<RawMaterial | null> {
    try {
      return await this.service.deleteRawMaterial(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Supplier, {
    nullable: true,
    name: "supplier",
  })
  async getSupplier(
    @graphql.Parent() parent: RawMaterial
  ): Promise<Supplier | null> {
    const result = await this.service.getSupplier(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
