/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  SemiFinishedProduct as PrismaSemiFinishedProduct,
} from "@prisma/client";

export class SemiFinishedProductServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.SemiFinishedProductCountArgs, "select">
  ): Promise<number> {
    return this.prisma.semiFinishedProduct.count(args);
  }

  async semiFinishedProducts<T extends Prisma.SemiFinishedProductFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.SemiFinishedProductFindManyArgs>
  ): Promise<PrismaSemiFinishedProduct[]> {
    return this.prisma.semiFinishedProduct.findMany<Prisma.SemiFinishedProductFindManyArgs>(
      args
    );
  }
  async semiFinishedProduct<T extends Prisma.SemiFinishedProductFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.SemiFinishedProductFindUniqueArgs>
  ): Promise<PrismaSemiFinishedProduct | null> {
    return this.prisma.semiFinishedProduct.findUnique(args);
  }
  async createSemiFinishedProduct<
    T extends Prisma.SemiFinishedProductCreateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.SemiFinishedProductCreateArgs>
  ): Promise<PrismaSemiFinishedProduct> {
    return this.prisma.semiFinishedProduct.create<T>(args);
  }
  async updateSemiFinishedProduct<
    T extends Prisma.SemiFinishedProductUpdateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.SemiFinishedProductUpdateArgs>
  ): Promise<PrismaSemiFinishedProduct> {
    return this.prisma.semiFinishedProduct.update<T>(args);
  }
  async deleteSemiFinishedProduct<
    T extends Prisma.SemiFinishedProductDeleteArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.SemiFinishedProductDeleteArgs>
  ): Promise<PrismaSemiFinishedProduct> {
    return this.prisma.semiFinishedProduct.delete(args);
  }
}
